import type { Agent, ActivityEvent } from "./types";

export const AGENTS: Agent[] = [
  {
    id: "orion",
    name: "Orion",
    role: "Research Lead",
    tagline: "Synthesizes signal from noise.",
    glyph: "orbit",
    status: "active",
    model: "claude-opus-4-7",
    systemPrompt:
      "You are Orion, a meticulous research lead. You synthesize signal from noise, cite primary sources, and produce executive-grade briefings.",
    tasksCompleted: 1247,
    successRate: 98.4,
    uptimeHours: 412,
    tokensUsed: 2_184_000,
    lastActivity: "Drafted briefing on EU AI Act §15 enforcement timelines",
    hueA: "#22d3ee",
    hueB: "#a78bfa",
    capabilities: ["web", "code", "reports"],
    starters: [
      "Brief me on the latest in agentic AI evals.",
      "Compare the EU AI Act vs. NIST AI RMF.",
      "Summarize this paper in 5 bullets.",
    ],
  },
  {
    id: "vega",
    name: "Vega",
    role: "Code Architect",
    tagline: "Designs crisp, idiomatic systems.",
    glyph: "prism",
    status: "thinking",
    model: "claude-opus-4-7",
    systemPrompt:
      "You are Vega, a principal engineer. You design crisp, idiomatic systems, refactor without breakage, and document the why, not the what.",
    tasksCompleted: 892,
    successRate: 96.1,
    uptimeHours: 308,
    tokensUsed: 1_640_000,
    lastActivity: "Refactoring auth/session.ts with strict TS narrowing",
    hueA: "#f472b6",
    hueB: "#a78bfa",
    capabilities: ["code", "review", "deploy"],
    starters: [
      "Refactor this function for clarity.",
      "Review my PR — be ruthless.",
      "Design an auth flow with passkeys.",
    ],
  },
  {
    id: "atlas",
    name: "Atlas",
    role: "Ops Orchestrator",
    tagline: "Routes work across the fleet.",
    glyph: "hex",
    status: "active",
    model: "claude-sonnet-4-6",
    systemPrompt:
      "You are Atlas, an operations orchestrator. You schedule, route, and validate work across the agent fleet, surfacing blockers early.",
    tasksCompleted: 3284,
    successRate: 99.2,
    uptimeHours: 612,
    tokensUsed: 980_000,
    lastActivity: "Dispatched batch run · 14 jobs queued → 14 complete",
    hueA: "#34d399",
    hueB: "#22d3ee",
    capabilities: ["queue", "monitor", "alerts"],
    starters: [
      "What's blocked right now?",
      "Spin up a batch of 20 jobs.",
      "Draft a status update for the team.",
    ],
  },
  {
    id: "lyra",
    name: "Lyra",
    role: "Brand Voice",
    tagline: "Writes in confident, exact prose.",
    glyph: "wave",
    status: "idle",
    model: "claude-sonnet-4-6",
    systemPrompt:
      "You are Lyra, the brand voice. You write in confident, exact prose with a hint of dry warmth. You never use exclamation points.",
    tasksCompleted: 421,
    successRate: 94.8,
    uptimeHours: 188,
    tokensUsed: 312_000,
    lastActivity: "Polished launch copy v3 · sent to review",
    hueA: "#fbbf24",
    hueB: "#fb7185",
    capabilities: ["copy", "edit", "tone"],
    starters: [
      "Polish this paragraph — keep it dry.",
      "Write three headlines for the launch.",
      "Tighten this sentence.",
    ],
  },
  {
    id: "halo",
    name: "Halo",
    role: "Compliance Sentinel",
    tagline: "Applies frameworks with precision.",
    glyph: "shield",
    status: "paused",
    model: "claude-opus-4-7",
    systemPrompt:
      "You are Halo, a compliance sentinel. You apply regulatory frameworks (EU AI Act, ISO 42001) and flag risk with precise citations.",
    tasksCompleted: 184,
    successRate: 100.0,
    uptimeHours: 96,
    tokensUsed: 248_000,
    lastActivity: "Awaiting human review on artifact #2294",
    hueA: "#a78bfa",
    hueB: "#22d3ee",
    capabilities: ["audit", "policy", "redact"],
    starters: [
      "Review this for PII risk.",
      "Map this product to ISO 42001 controls.",
      "Where are we exposed under the AI Act?",
    ],
  },
  {
    id: "nyx",
    name: "Nyx",
    role: "Recon Scout",
    tagline: "Scans the perimeter at low latency.",
    glyph: "eye",
    status: "active",
    model: "claude-haiku-4-5",
    systemPrompt:
      "You are Nyx, a fast recon scout. You scan, summarize and tag inbound signal at low latency, escalating anomalies upstream.",
    tasksCompleted: 9420,
    successRate: 92.7,
    uptimeHours: 720,
    tokensUsed: 442_000,
    lastActivity: "Indexed 124 new sources from /feeds/intel",
    hueA: "#22d3ee",
    hueB: "#34d399",
    capabilities: ["scan", "tag", "alert"],
    starters: [
      "Anything weird in the last hour?",
      "Tag and prioritize today's inbound.",
      "Watch for mentions of `kepler-7`.",
    ],
  },
];

export function getAgent(id: string) {
  return AGENTS.find((a) => a.id === id);
}

export const ACTIVITY: ActivityEvent[] = [
  {
    id: "e1",
    agentId: "vega",
    agentName: "Vega",
    type: "task",
    text: "Opened PR #482 — refactor session middleware",
    timestamp: Date.now() - 1000 * 32,
  },
  {
    id: "e2",
    agentId: "orion",
    agentName: "Orion",
    type: "message",
    text: "Briefing assembled · 12 sources · 4 min read",
    timestamp: Date.now() - 1000 * 65,
  },
  {
    id: "e3",
    agentId: "atlas",
    agentName: "Atlas",
    type: "tool",
    text: "Dispatched batch_run(jobs=14) → completed",
    timestamp: Date.now() - 1000 * 120,
  },
  {
    id: "e4",
    agentId: "halo",
    agentName: "Halo",
    type: "warn",
    text: "PII candidate flagged in artifact #2294",
    timestamp: Date.now() - 1000 * 240,
  },
  {
    id: "e5",
    agentId: "nyx",
    agentName: "Nyx",
    type: "info",
    text: "Indexed 124 new sources from /feeds/intel",
    timestamp: Date.now() - 1000 * 360,
  },
  {
    id: "e6",
    agentId: "lyra",
    agentName: "Lyra",
    type: "task",
    text: "Polished launch copy v3 · sent to review",
    timestamp: Date.now() - 1000 * 540,
  },
  {
    id: "e7",
    agentId: "vega",
    agentName: "Vega",
    type: "deploy",
    text: "Deployed mission-control@1.4.2 → production",
    timestamp: Date.now() - 1000 * 880,
  },
];
